apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-nginx-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-nginx-gateway
  template:
    metadata:
      labels:
        app: backend-nginx-gateway
    spec:
      containers:
        - name: backend-nginx-gateway
          image: nzhussup/backend-nginx-gateway:latest
          ports:
            - containerPort: 8082
          env:
            - name: NGINX_GATEWAY_LISTEN_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_LISTEN_PORT
            - name: NGINX_GATEWAY_BASE_UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_BASE_UPSTREAM_HOST
            - name: NGINX_GATEWAY_BASE_UPSTREAM_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_BASE_UPSTREAM_PORT
            - name: NGINX_GATEWAY_IMAGE_UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_IMAGE_UPSTREAM_HOST
            - name: NGINX_GATEWAY_IMAGE_UPSTREAM_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_IMAGE_UPSTREAM_PORT
            - name: NGINX_GATEWAY_LLM_UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_LLM_UPSTREAM_HOST
            - name: NGINX_GATEWAY_LLM_UPSTREAM_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_LLM_UPSTREAM_PORT
            - name: NGINX_GATEWAY_ACCOUNT_UPSTREAM_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_ACCOUNT_UPSTREAM_HOST
            - name: NGINX_GATEWAY_ACCOUNT_UPSTREAM_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-gateway-config
                  key: NGINX_GATEWAY_ACCOUNT_UPSTREAM_PORT
            - name: NGINX_GATEWAY_RESOLVER
              value: kube-dns.kube-system.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: backend-nginx-gateway
spec:
  selector:
    app: backend-nginx-gateway
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
