apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-base-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-base-service
  template:
    metadata:
      labels:
        app: backend-base-service
    spec:
      containers:
        - name: backend-base-service
          image: nzhussup/backend-base-service:latest
          ports:
            - containerPort: 8010
          env:
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: DB_HOST
            - name: SPRING_DATASOURCE_DB
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: DB_NAME
            - name: SPRING_DATASOURCE_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: DB_PORT
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: DB_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_PORT
            - name: KEYCLOAK_BACKEND_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BACKEND_CLIENT_ID
            - name: KEYCLOAK_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_JWK_SET_URI
            - name: KEYCLOAK_EXPECTED_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BACKEND_CLIENT_ID

---
apiVersion: v1
kind: Service
metadata:
  name: backend-base-service
spec:
  type: ClusterIP
  ports:
    - port: 8010
      targetPort: 8010
  selector:
    app: backend-base-service
