apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-llm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-llm-service
  template:
    metadata:
      labels:
        app: backend-llm-service
    spec:
      containers:
        - name: backend-llm-service
          image: nzhussup/backend-llm-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: GIN_MODE
              value: "release"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_PORT
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: API_GATEWAY_URL
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: OPENROUTER_API_KEY
            - name: OPENROUTER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: OPENROUTER_API_URL

---
apiVersion: v1
kind: Service
metadata:
  name: backend-llm-service
spec:
  selector:
    app: backend-llm-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
