apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-image-service
  template:
    metadata:
      labels:
        app: backend-image-service
    spec:
      containers:
        - name: backend-image-service
          image: nzhussup/backend-image-service:latest
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: images-volume
              mountPath: /app/var/images
          env:
            - name: GIN_MODE
              value: "release"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: REDIS_PORT
            - name: KEYCLOAK_BACKEND_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BACKEND_CLIENT_ID
            - name: KEYCLOAK_JWK_SET_URL
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_JWK_SET_URL
            - name: KEYCLOAK_EXPECTED_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_BACKEND_CLIENT_ID

      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: backend-image-service-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend-image-service
spec:
  selector:
    app: backend-image-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
