apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-redis-config
data:
  redis.conf: |
    save 900 1
    save 300 10
    save 60 10000

    loglevel notice

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-redis-server
  template:
    metadata:
      labels:
        app: backend-redis-server
    spec:
      volumes:
        - name: redis-config
          configMap:
            name: backend-redis-config
      containers:
        - name: backend-redis-server
          image: redis:7.4
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

---
apiVersion: v1
kind: Service
metadata:
  name: backend-redis-server
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: backend-redis-server
