apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api-gateway
  template:
    metadata:
      labels:
        app: backend-api-gateway
    spec:
      containers:
        - name: backend-api-gateway
          image: nzhussup/backend-api-gateway:latest
          ports:
            - containerPort: 8082
          env:
            - name: GIN_MODE
              value: "release"
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: AUTH_SERVICE_URL
            - name: BASE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: BASE_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: USER_SERVICE_URL
            - name: IMAGE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: IMAGE_SERVICE_URL
            - name: LLM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: LLM_SERVICE_URL
            - name: WEDDING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: WEDDING_SERVICE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-gateway
spec:
  selector:
    app: backend-api-gateway
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
