apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin-panel
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin-panel
  template:
    metadata:
      labels:
        app: web-admin-panel
    spec:
      containers:
        - name: web-admin-panel
          image: nzhussup/web-admin-panel:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: web-admin-panel-service
  namespace: default
spec:
  selector:
    app: web-admin-panel
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8000
  type: ClusterIP
