apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-controller
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      monitoring-role: ingress-nginx-metrics
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s