apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: kube-prometheus
  name: ingress-nginx-controller
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      monitoring-role: ingress-nginx-metrics
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
