apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nzhussup/go-api-gateway:latest
          ports:
            - containerPort: 8082
          env:
            - name: GIN_MODE
              value: "release"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.default.svc.cluster.local:8083"
            - name: BASE_SERVICE_URL
              value: "http://base-service.default.svc.cluster.local:8010"
            - name: USER_SERVICE_URL
              value: "http://user-service.default.svc.cluster.local:8084"
            - name: IMAGE_SERVICE_URL
              value: "http://image-service.default.svc.cluster.local:8085"
            - name: LLM_SERVICE_URL
              value: "http://llm-service.default.svc.cluster.local:8086"
            - name: WEDDING_SERVICE_URL
              value: "http://wedding-backend-service.default.svc.cluster.local:9090"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
