apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nzhussup/auth-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_HOST
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-panel-secrets
                  key: DB_PASSWORD
            - name: SECURITY_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-panel-secrets
                  key: JWT_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: auth-service
