apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-service
  template:
    metadata:
      labels:
        app: base-service
    spec:
      containers:
        - name: base-service
          image: nzhussup/base-service:latest
          ports:
            - containerPort: 8010
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service.default.svc.cluster.local:8083"
            - name: SPRING_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_HOST
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-panel-secrets
                  key: DB_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: REDIS_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: base-service
spec:
  type: ClusterIP
  ports:
    - port: 8010
      targetPort: 8010
  selector:
    app: base-service
