apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  KEYCLOAK_HOSTNAME: auth.nzhussup.dev

  KEYCLOAK_REALM_ID: backend-auth
  KEYCLOAK_REALM_NAME: backend-auth
  KEYCLOAK_REALM_DISPLAY_NAME: Backend Auth

  KEYCLOAK_SSL_REQUIRED: external
  KEYCLOAK_REGISTRATION_ALLOWED: "true"
  KEYCLOAK_LOGIN_WITH_EMAIL_ALLOWED: "true"
  KEYCLOAK_RESET_PASSWORD_ALLOWED: "true"
  KEYCLOAK_REMEMBER_ME: "true"
  KEYCLOAK_VERIFY_EMAIL: "false"

  KEYCLOAK_BACKEND_CLIENT_ID: backend-auth-client
  KEYCLOAK_BACKEND_CLIENT_NAME: Backend Auth Client
  KEYCLOAK_BACKEND_STANDARD_FLOW_ENABLED: "false"
  KEYCLOAK_BACKEND_DIRECT_ACCESS_GRANTS_ENABLED: "false"

  KEYCLOAK_FRONTEND_CLIENT_ID: frontend-admin-auth-client
  KEYCLOAK_FRONTEND_CLIENT_NAME: Frontend Admin Auth Client
  KEYCLOAK_FRONTEND_ROOT_URL: https://admin.nzhussup.dev
  KEYCLOAK_FRONTEND_BASE_URL: https://admin.nzhussup.dev
  KEYCLOAK_FRONTEND_REDIRECT_URIS_JSON: '["https://admin.nzhussup.dev/*","https://admin.nzhussup.com/*","https://nzhussup.dev/*","https://nzhussup.com/*"]'
  KEYCLOAK_FRONTEND_WEB_ORIGINS_JSON: '["https://admin.nzhussup.dev","https://admin.nzhussup.com","https://nzhussup.dev","https://nzhussup.com"]'

  KEYCLOAK_JWK_SET_URI: https://auth.nzhussup.dev/realms/backend-auth/protocol/openid-connect/certs
  KEYCLOAK_JWK_SET_URL: https://auth.nzhussup.dev/realms/backend-auth/protocol/openid-connect/certs

  KEYCLOAK_INTERNAL_URL: http://backend-keycloak-server.default.svc.cluster.local:8080
  KEYCLOAK_ADMIN_REALM: master
  KEYCLOAK_ACCOUNT_SERVICE_ADMIN_CLIENT_ID: account-service-admin