apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: default
data:
  NGINX_GATEWAY_LISTEN_PORT: "8082"

  NGINX_GATEWAY_BASE_UPSTREAM_HOST: backend-base-service
  NGINX_GATEWAY_BASE_UPSTREAM_PORT: "8010"

  NGINX_GATEWAY_IMAGE_UPSTREAM_HOST: backend-image-service
  NGINX_GATEWAY_IMAGE_UPSTREAM_PORT: "8085"

  NGINX_GATEWAY_LLM_UPSTREAM_HOST: backend-llm-service
  NGINX_GATEWAY_LLM_UPSTREAM_PORT: "8086"

  NGINX_GATEWAY_ACCOUNT_UPSTREAM_HOST: backend-account-service
  NGINX_GATEWAY_ACCOUNT_UPSTREAM_PORT: "8087"

  NGINX_GATEWAY_URL: http://backend-nginx-gateway.default.svc.cluster.local:8082