apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user-service
  template:
    metadata:
      labels:
        app: backend-user-service
    spec:
      containers:
        - name: backend-user-service
          image: nzhussup/backend-user-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: AUTH_SERVICE_URL
              value: "http://backend-auth-service.default.svc.cluster.local:8083"
            - name: SPRING_DATASOURCE_HOST
              value: local-db-service:5555/admin_db
            - name: SPRING_DATASOURCE_USERNAME
              value: "nurik"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: backend-user-service
