apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-service-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/images"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-service-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi