apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: platform-logging
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    frontend:
      max_outstanding_per_tenant: 4096

    query_range:
      parallelise_shardable_queries: false

    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      filesystem:
        directory: /loki/chunks

    compactor:
      working_directory: /loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      delete_request_store: filesystem

    limits_config:
      split_queries_by_interval: 30m
      retention_period: 168h

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules-tmp
      ring:
        kvstore:
          store: inmemory
      enable_api: true
