name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create release for (e.g., v2.8.0)"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract changelog entry for tag
        id: changelog
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Manual run - use input or fail if missing
            TAG="${{ github.event.inputs.tag }}"
            if [ -z "$TAG" ]; then
              echo "❌ 'tag' input is required for manual runs"
              exit 1
            fi
            TAG_STRIPPED="${TAG#v}"
          else
            # Push event - extract tag from ref
            if [[ "$GITHUB_REF" != refs/tags/* ]]; then
              echo "❌ Not a tag push — skipping changelog extraction."
              exit 1
            fi
            TAG="${GITHUB_REF#refs/tags/}"
            TAG_STRIPPED="${TAG#v}"
          fi

          echo "Extracting changelog for tag: $TAG_STRIPPED"

          ENTRY=$(awk -v tag="$TAG_STRIPPED" '
            BEGIN { in_section = 0 }
            # Start capturing at "# [tag]", "## [tag]", or "### [tag]"
            $0 ~ "^#+ \\[" tag "\\]" { in_section = 1; next }
            # Stop capturing at the next heading line with a version
            in_section && $0 ~ /^#+ \[[0-9]+\.[0-9]+\.[0-9]+/ { exit }
            in_section { print }
          ' CHANGELOG.md)

          if [ -z "$ENTRY" ]; then
            echo "❌ No changelog entry found for $TAG_STRIPPED"
            echo "Available versions:"
            grep -E '^#+ \[[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md
            exit 1
          fi

          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$ENTRY" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: ${{ github.event.inputs.tag || github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
